image: python3:latest

# Default environment variables
variables:
  # Change pip's cache directory to be inside the project directory since we
  # can only cache local items.
  PIP_CACHE_DIR: "$CI_PROJECT_ID/.cache/.pip"
  SCAN_DIR: "../.scan"
  # Always use a fresh clone so submodule doesn't break.
  GIT_STRATEGY: clone

stages:
  - check
  - build

cache:
  paths:
    - .cache/.pip
    - gunyah-venv/
    - .qcom-root-g2.crt

before_script:
  - python3 -m venv gunyah-venv
  - source gunyah-venv/bin/activate

code style:
  stage: check
  tags:
    - gunyah
  script:
    - pip install flake8
    - pip install autopep8
    - git ls-files -- '*.py' | xargs autopep8 -i
    - git ls-files -- '*.py' | xargs flake8
    - git ls-files -- '*.[ch]' | xargs $LLVM/bin/clang-format --style=file -i
    - git diff --exit-code

git checks:
  stage: check
  tags:
    - gunyah
  script:
    - git fetch origin master
    - git diff --check origin/master HEAD

build:
 stage: build
 tags:
    - gunyah
 script:
    - ./.gitlab-ci-build-setup.sh
    - ./configure.py
    - scons
